name: "_[Airflow] Tests"

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    name: "Tests unitaires des DAGs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.12.1"
      - name: Install Dependencies
        run: pip install --require-hashes --no-deps -r airflow-requirements.txt -r dev-requirements.txt
      # TODO: voir pourquoi on ne peut pas lancer les tests ici
      # 1. On avait d'abord une erreur pydantic
      # J'ai donc instalé la dépendance
      # ERROR: while parsing the following warning configuration:

      #   ignore::pydantic.warnings.PydanticDeprecatedSince20

      # This error occurred:

      # Traceback (most recent call last):
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1917, in parse_warning_filter
      #     category: type[Warning] = _resolve_warning_category(category_)
      #                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1955, in _resolve_warning_category
      #     m = __import__(module, None, None, [klass])
      #         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      # ModuleNotFoundError: No module named 'pydantic'
      #
      #
      #
      # Puis j'ai eu de nouvelles erreurs car pytests lit le pyproject.toml
      # Traceback (most recent call last):
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/bin/pytest", line 8, in <module>
      #     sys.exit(console_main())
      #              ^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 201, in console_main
      #     code = main()
      #            ^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 156, in main
      #     config = _prepareconfig(args, plugins)
      #              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
      #     config = pluginmanager.hook.pytest_cmdline_parse(
      #              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
      #     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
      #            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
      #     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
      #            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
      #     raise exception.with_traceback(exception.__traceback__)
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
      #     teardown.throw(exception)  # type: ignore[union-attr]
      #     ^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
      #     config = yield
      #              ^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
      #     res = hook_impl.function(*args)
      #           ^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
      #     self.parse(args)
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1494, in parse
      #     self._preparse(args, addopts=addopts)
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
      #     self.hook.pytest_load_initial_conftests(
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
      #     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
      #            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
      #     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
      #            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
      #     raise exception.with_traceback(exception.__traceback__)
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
      #     teardown.throw(exception)  # type: ignore[union-attr]
      #     ^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
      #     return (yield)
      #             ^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
      #     teardown.throw(exception)  # type: ignore[union-attr]
      #     ^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
      #     yield
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
      #     res = hook_impl.function(*args)
      #           ^^^^^^^^^^^^^^^^^^^^^^^^^
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pytest_django/plugin.py", line 356, in pytest_load_initial_conftests
      #     with _handle_import_error(_django_project_scan_outcome):
      #   File "/Users/fabienlefrapper/.local/share/mise/installs/python/3.12.5/lib/python3.12/contextlib.py", line 158, in __exit__
      #     self.gen.throw(value)
      #   File "/Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets/.venv/lib/python3.12/site-packages/pytest_django/plugin.py", line 184, in _handle_import_error
      #     raise ImportError(msg) from None
      # ImportError: No module named 'decouple'

      # pytest-django found a Django project in /Users/fabienlefrapper/Developer/beta.gouv.fr/quefairedemesobjets (it contains manage.py) and added it to the Python path.
      # If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
      # - name: Run unit tests
      #   run: pytest dags_unit_tests
